export default {
  // 复制
  iconfuzhi: '\ue6ac',
  // 切换语言
  iconqiehuanyuyan: '\ue6af',
  // 等级费率
  icondengjifeishuai: '\ue60c',
  // 关于我们
  iconguanyuwomen: '\ue60d',
  // 黑名单
  iconheimingdan: '\ue60e',
  // 安全设置
  iconanquanshezhi: '\ue60f',
  // 主题设置
  iconzhutishezhi: '\ue610',
  // 身份杨振
  iconshenfenyanzheng: '\ue611',
  // 在线客服
  iconzaixiankefu: '\ue612',
  // 消息中心
  iconxiaoxizhongxin: '\ue613',
  // 邀请返佣
  iconyaoqingfanyong: '\ue614',
  // 我的广告
  iconwodeguanggao: '\ue615',
  // 安全设置
  iconanquanshezhibai: '\ue6aa',
  // 列表右箭头
  icondianji: '\ue6d8',
  // 我得工单
  iconwodegongdan: '\ue6ad',
  // 新手考核
  iconxinshoukaohe: '\ue6ae',
  // 环境切换
  iconqiehuan1: '\ue6db',
  // 币币自选
  'iconbibi-zixuan': '\ue6b6',
  // 返回
  iconfanhui: '\ue6e1',
  // 币币展开交易对
  iconqiehuanjiaoyidui: '\ue6e0',
  // 空状态
  iconkongzhuangtai: '\ue6b4',
  // 币币未收藏
  iconzixuanweixuanzhong: '\ue6ea',
  // 币币收藏
  iconzixuanxuanzhong: '\ue6eb',
  // 难过
  iconnanguo: '\ue64e',
  // 中文
  iconqiehuanyuyanzhongwen: '\ue6f1',
  // 语言切换
  iconqiehuanyuyan2: '\ue708',
  // 选中
  iconxuanzhong1: '\ue6e8',
}
